/**
 * Static snapshot of Pinecone `program_name` / `factory_name` values.
 * Regenerate: `python3 scripts/list_program_factory_facets.py` in poggesi-ai, then paste
 * `program_names` / `factory_names` here. Search still sends the chosen value via `program_name` /
 * `factory_name` query parameters to the backend (exact metadata match).
 */
export const CATALOG_PROGRAM_NAMES: readonly string[] = [
  '2BRICK - FURNITURE QUOTE- BB',
  'AH- Furniture Quote - GK',
  'AL_ Chaise',
  'Alba',
  'ALM FURNITURE QUOTE',
  'AZ - Umbrellas',
  "BALI Cabana 8x8'",
  'BALI CABANA QUOTE - BB，ST - KNX',
  'Biltmore Country Club',
  'Boho Collection - FN - QUOTE',
  'Bolt Down Bench – Design Bridge',
  'CCL new ship',
  'Cento',
  'chaise lounge',
  'Chaise Lounger and Accent Tables – FAIRMONT',
  'CHAISES - HRSJ - FN - QUOTE',
  'Chiara',
  'CIFF chair',
  'concrete Table - Inquiry - RWLV',
  'Custom Pool Chair- BB',
  'Desio',
  'Dining Chairs with Adjusted Seat Heights',
  'Dining Table - Rooftop - FN - QUOTE',
  'Ferrara',
  'Ferrara Bar Table - FN - QUOTE',
  'Fiorenza',
  'Funiture Quote',
  'FURNITURE QUOTE -GRC side table',
  'Furniture Quote- PPG- ST',
  'FURNITURE QUOTE-teak wood chaise lounge',
  'GranC - Furniture Quote - LD',
  'In-pool Chaise Lounger Ideas - BB',
  'ISC - FURNITURE QUOTE - BB',
  'Isola',
  'KCI -Furniture Quote - GK',
  "KENO_ Umbrellas 9' QUOTE-GK",
  'Lazio',
  'Lifestyles - Chair Quote - GK',
  'Longhorn Bench - Quote',
  'LW - FURNITURE QUOTE - BB',
  'Modena',
  'Modena Single Chaise Lounge - Side Table',
  'Multiple Items - ARIA - FN - QUOTE',
  'Multiple Items - DREAM',
  'MULTIPLE ITEMS - HRS - FN',
  'Multiple Items - HRSJ - FN',
  'Multiple Items-Montage KB',
  'NCL PRESTIGE CO-SU-05 Lounge chair',
  'NOE RM- Furniture Quote - LD',
  'Novara',
  'Outdoor chair and Barstool',
  'Palermo',
  'Palermo Dinning Table',
  'Pavia',
  'Picnic Tables - FN - QUOTE',
  'Poggesi Order Summary',
  'Prestige Tables - NCL',
  'Raised Vent_Umbrella',
  'RCJPC - Furniture Quote- GK',
  'Reggio',
  'RESIN CHAIRS - HRS - FN - QUOTE',
  'ROYCH - Furniture Quote- GK',
  'Sarno',
  'Showroom Furniture Inquiry',
  'Simple Dining Chairs - AO - FN - QUOTE',
  'Stella',
  'Trattino',
  'Trento',
  'Veneto',
  'VOLANDAM - BALCONY FURNITURE+A729:A743'
] as const

export const CATALOG_FACTORY_NAMES: readonly string[] = ['GRC', 'Great', 'JW', 'MX', 'Union'] as const
